# Generated by Django 2.2.10 on 2020-05-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofileinfo',
            name='product_key',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ProductKey'),
        ),
        migrations.AlterField(
            model_name='employeeprofileinfo',
            name='avatar',
            field=models.ImageField(upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='employeeprofileinfo',
            name='product_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProductKey'),
        ),
        migrations.AlterField(
            model_name='productkey',
            name='product_key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
