# Generated by Django 2.2.10 on 2020-05-30 02:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200527_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofileinfo',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employeeprofileinfo',
            name='avatar',
            field=models.ImageField(upload_to=accounts.models.update_filename),
        ),
    ]
